# Basic
title: Peanut
subtitle: A blog for peanut
welcome_message:  Peanut no peanut ！
description: Every man is his own worst enemy.
creator: <a href="https://github.com/peanut-w">@peanut</a>

url: "https://github.com/peanut-w"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 博客

# Navigation buttons in the front page.
# 我的项目指向我的git
nav:
    - {title: Book, description: 简书, url: 'https://www.jianshu.com/u/3b5aecf0a808'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: http://weibo.com/pppeanut
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: 18832016332@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
